### ISSUE TITLE
02-ospsuiteR, slide 5/31

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/r-packages-training#20]
![image](https://github.com/esqLABS/r-packages-training/assets/25903040/7c052721-b1ab-44f3-b13b-620763bbb8e4)

**Comment by Felixmil** [comment]
It looks ok in latest renders:
![image](https://github.com/esqLABS/r-packages-training/assets/34234913/3419aac7-6ca2-4eeb-9a0b-904c76f9b9aa)

**Comment by PavelBal** [comment]
Yes, I didn't have the latest TLF.
